### ISSUE TITLE
Weather Script

### ISSUE THREAD

**Issue by ArNz8o8** [Xeon3D/textual5-scripts#2]
Yahoo updated his API with the use of a new URL. Can you update the Textual weather script to this?

https://developer.yahoo.com/weather/

Thanks!

**Comment by Xeon3D** [comment]
Ill give it a go later, but you could do it yourself too and send me a pull request

**Comment by ArNz8o8** [comment]
I tried.. but seems to need an oath key.. can't figure it out yet :)

**Comment by Xeon3D** [comment]
OK, I'll have a look at it later at night. Haven't touched my scripts in a
long time though, let's hope I can still code something...

**Comment by ArNz8o8** [comment]
Thanks man, looking forward to it! :+1:

**Comment by ArNz8o8** [comment]
Any news?

**Comment by Xeon3D** [comment]
I gave it a look, and to be honest there's much more change to it than I anticipated. 
In case you didn't notice, the scripts are unsupported, so feel free to edit it and submit a pull request, or fork it...
