### ISSUE TITLE
"OS X" On Sierra

### ISSUE THREAD

**Issue by iAdam1n** [Xeon3D/textual5-scripts#3]
Can you please make the script say "macOS" if running Sierra? Thanks.

**Comment by Xeon3D** [comment]
I'm sure you could do it yourself... its two lines of code.

**Comment by iAdam1n** [comment]
https://github.com/Xeon3D/textual5-scripts/pull/5

**Comment by Xeon3D** [comment]
Fixed by iAdam1n
