### ISSUE TITLE
si Broken on Textual 6

### ISSUE THREAD

**Issue by iAdam1n** [Xeon3D/textual5-scripts#6]
I'm getting "Script Execution Failure (si.scpt: (no input)): /Users/iAdam1n/Library/Application Scripts/com.codeux.apps.textual/si.scpt: execution error: No error. (-1708)" since upgrading to Textual 6.

**Comment by Xeon3D** [comment]
Of course you are. And if you read the description you'll see that they are unmaintained as I don't own a Mac nor mackintosh anymore. Feel free to fix it and I'll commit the pull request
